#!/usr/bin/env bash
# Grapheme cluster width check.
#
# Each row prints a cluster between brackets, then pads to the width the
# reference VT (ghostty-vt) measured for it. If this terminal agrees, every
# trailing | lands in one column. A | out of column is a width disagreement
# for that row, and the W column says what was expected.
#
# Some rows contain invisible characters (zero width space, joiners, soft
# hyphen). They are meant to look empty; only the marker position matters.

set -u
printf "\n  %-26s %-3s %s\n" "CASE" "W" "RENDERED (| must align)"
printf "  %-26s %-3s %s\n" "--------------------------" "---" "----------------------"
printf "\n  \033[1m%s\033[0m\n" "cjk-fullwidth"
printf "  %-26s %-3s [%s]          |\n" "cjk-han" "2" "世"
printf "  %-26s %-3s [%s]          |\n" "cjk-kana" "2" "あ"
printf "  %-26s %-3s [%s]          |\n" "fullwidth-latin" "2" "Ａ"
printf "  %-26s %-3s [%s]           |\n" "halfwidth-kana" "1" "ｱ"
printf "  %-26s %-3s [%s]          |\n" "cjk-ext-b-smp" "2" "𠀀"
printf "\n  \033[1m%s\033[0m\n" "hangul"
printf "  %-26s %-3s [%s]          |\n" "hangul-syllable" "2" "한"
printf "  %-26s %-3s [%s]          |\n" "hangul-jamo-conjoining" "2" "각"
printf "  %-26s %-3s [%s]          |\n" "hangul-jamo-lead-alone" "2" "ᄀ"
printf "  %-26s %-3s [%s]          |\n" "hangul-compat-jamo" "2" "ㄱ"
printf "\n  \033[1m%s\033[0m\n" "emoji-basic"
printf "  %-26s %-3s [%s]          |\n" "emoji-simple" "2" "😀"
printf "\n  \033[1m%s\033[0m\n" "emoji-zwj"
printf "  %-26s %-3s [%s]          |\n" "emoji-zwj-family" "2" "👨‍👩‍👧‍👦"
printf "  %-26s %-3s [%s]          |\n" "emoji-zwj-profession" "2" "👩‍💻"
printf "  %-26s %-3s [%s]          |\n" "emoji-zwj-rainbow" "2" "🏳️‍🌈"
printf "  %-26s %-3s [%s]          |\n" "emoji-family-skin-tones" "2" "👩🏻‍🤝‍👨🏿"
printf "\n  \033[1m%s\033[0m\n" "emoji-flags"
printf "  %-26s %-3s [%s]          |\n" "emoji-flag" "2" "🇯🇵"
printf "  %-26s %-3s [%s]        |\n" "emoji-two-flags" "4" "🇯🇵🇺🇸"
printf "  %-26s %-3s [%s]          |\n" "emoji-tag-flag" "2" "🏴󠁧󠁢󠁳󠁣󠁴󠁿"
printf "  %-26s %-3s [%s]          |\n" "emoji-ri-odd" "2" "🇯"
printf "\n  \033[1m%s\033[0m\n" "emoji-keycap"
printf "  %-26s %-3s [%s]          |\n" "emoji-keycap" "2" "1️⃣"
printf "  %-26s %-3s [%s]           |\n" "emoji-keycap-no-vs" "1" "1⃣"
printf "\n  \033[1m%s\033[0m\n" "emoji-skin-tone"
printf "  %-26s %-3s [%s]          |\n" "emoji-skin-tone" "2" "👍🏽"
printf "  %-26s %-3s [%s]          |\n" "emoji-modifier-alone" "2" "🏽"
printf "\n  \033[1m%s\033[0m\n" "variation-selectors"
printf "  %-26s %-3s [%s]          |\n" "vs16-emoji-presentation" "2" "❤️"
printf "  %-26s %-3s [%s]           |\n" "vs15-text-presentation" "1" "❤︎"
printf "  %-26s %-3s [%s]          |\n" "emoji-vs16-digit" "2" "#️"
printf "\n  \033[1m%s\033[0m\n" "combining"
printf "  %-26s %-3s [%s]           |\n" "combining-acute" "1" "é"
printf "  %-26s %-3s [%s]           |\n" "combining-stack" "1" "ẹ̀́"
printf "  %-26s %-3s [%s]           |\n" "combining-zalgo" "1" "ạ̤̥̰̱̀́̂̃̈̊"
printf "  %-26s %-3s [%s]           |\n" "thai-combining" "1" "ก้"
printf "  %-26s %-3s [%s]           |\n" "hebrew-point" "1" "אַ"
printf "  %-26s %-3s [%s]            |\n" "combining-mark-alone" "0" "́"
printf "\n  \033[1m%s\033[0m\n" "devanagari"
printf "  %-26s %-3s [%s]           |\n" "devanagari-consonant" "1" "न"
printf "  %-26s %-3s [%s]          |\n" "devanagari-ksha" "2" "क्ष"
printf "  %-26s %-3s [%s]          |\n" "devanagari-matra" "2" "नि"
printf "\n  \033[1m%s\033[0m\n" "arabic"
printf "  %-26s %-3s [%s]           |\n" "arabic-isolated" "1" "ا"
printf "  %-26s %-3s [%s]        |\n" "arabic-word" "4" "سلام"
printf "  %-26s %-3s [%s]          |\n" "arabic-lam-alef" "2" "لا"
printf "\n  \033[1m%s\033[0m\n" "zero-width"
printf "  %-26s %-3s [%s]          |\n" "zero-width-non-joiner" "2" "ب‌ة"
printf "  %-26s %-3s [%s]          |\n" "zero-width-no-break-space" "2" "a﻿b"
printf "  %-26s %-3s [%s]          |\n" "zero-width-space" "2" "a​b"
printf "  %-26s %-3s [%s]            |\n" "zero-width-space-alone" "0" "​"
printf "  %-26s %-3s [%s]            |\n" "zero-width-joiner-alone" "0" "‍"
printf "  %-26s %-3s [%s]         |\n" "soft-hyphen" "3" "a­b"
printf "\n  \033[1m%s\033[0m\n" "box-block"
printf "  %-26s %-3s [%s]           |\n" "box-drawing-light" "1" "─"
printf "  %-26s %-3s [%s]           |\n" "block-full" "1" "█"

printf "\n  All | in one column means widths match the reference.\n\n"
